import { Task } from "models/Task.interface"

export const GLOBAL_TASKS_LIST: Array<Partial<Task>> = [
  {
    id: 11,
    jobNumber: 9993939,
    processName: "Produce MPEG",
    name: "Stich MPEG",
    dueDate: "10/21/2021",
    status: "assigned",
    priority: "urgent",
    earliestVideoOrderDays: 15,
    earliestVideoOrderDueDate: "11/18/2021",
    division: "South Carolina",
    assignedTo: "gjames",
    caseName: "",
    comments: [
      {
        id: 1,
        title: "Comment 1",
        description: "First Comment for task Stich MPEG",
        createdBy: "gjames@veritext.com",
      },
      {
        id: 2,
        title: "Comment 2",
        description: "Second Comment for task Stich MPEG",
        createdBy: "gjames@veritext.com",
      },
    ],
    history: [
      {
        id: 1,
        description: "Assigned to gjames",
        date: "11/1/2021",
      },
      {
        id: 2,
        description: "Claimed by cgalinda",
        date: "11/2/2021",
      },
    ],
  },
  {
    id: 12,
    jobNumber: 4520002,
    processName: "Produce MPEG 2",
    name: "Stich MPEG normal Task",
    dueDate: "10/21/2021",
    status: "assigned",
    priority: "normal",
    earliestVideoOrderDays: 5,
    earliestVideoOrderDueDate: "11/5/2021",
    division: "South Carolina",
    assignedTo: "gjames",
    caseName: "",
    comments: [
      {
        id: 1,
        title: "Comment 1",
        description: "First Comment for task Stich MPEG normal Task",
        createdBy: "gjames@veritext.com",
      },
      {
        id: 2,
        title: "Comment 2",
        description: "Second Comment for task Stich MPEG normal Task",
        createdBy: "gjames@veritext.com",
      },
    ],
    history: [
      {
        id: 1,
        description: "Assigned to gjames",
        date: "11/1/2021",
      },
      {
        id: 2,
        description: "Claimed by cgalinda",
        date: "11/2/2021",
      },
    ],
  },
  {
    id: 1,
    jobNumber: 4544414,
    processName: "Produce MPEG",
    name: "QC Original Files",
    dueDate: "10/21/2021",
    status: "assigned",
    priority: "normal",
    earliestVideoOrderDays: 10,
    earliestVideoOrderDueDate: "10/18/2021",
    caseName: "Dorsey, Bessie Et Al. v. Lm General Insurance Company",
    division: "Maryland",
    assignedTo: "mdrenkalo",
    comments: [
      {
        id: 1,
        title: "Comment 1",
        description: "First Comment for task QC Original Files",
        createdBy: "gjames@veritext.com",
      },
      {
        id: 2,
        title: "Comment 2",
        description: "Second Comment for task QC Original Files",
        createdBy: "gjames@veritext.com",
      },
    ],
    history: [
      {
        id: 1,
        description: "Assigned to gjames",
        date: "11/1/2021",
      },
      {
        id: 2,
        description: "Claimed by cgalinda",
        date: "11/2/2021",
      },
    ],
  },
  {
    id: 2,
    jobNumber: 4572355,
    processName: "Produce MPEG",
    name: "Review/ QC Files/ Prepare PIP Video",
    dueDate: "10/20/2021",
    status: "overdue",
    priority: "urgent",
    earliestVideoOrderDays: 10,
    earliestVideoOrderDueDate: "10/18/2021",
    caseName: "In Re Brenn De Bree, Et Al.",
    division: "Houston",
    assignedTo: "",
    comments: [
      {
        id: 1,
        title: "Comment 1",
        description:
          "First Comment for task Review/ QC Files/ Prepare PIP Video",
        createdBy: "gjames@veritext.com",
      },
      {
        id: 2,
        title: "Comment 2",
        description:
          "Second Comment for task Review/ QC Files/ Prepare PIP Video",
        createdBy: "gjames@veritext.com",
      },
    ],
    history: [
      {
        id: 1,
        description: "Assigned to gjames",
        date: "11/1/2021",
      },
      {
        id: 2,
        description: "Claimed by cgalinda",
        date: "11/2/2021",
      },
    ],
  },
  {
    id: 3,
    jobNumber: 4520003,
    processName: "Produce MPEG",
    name: "Stich MPEG",
    dueDate: "10/21/2021",
    status: "assigned",
    priority: "high",
    earliestVideoOrderDays: 10,
    earliestVideoOrderDueDate: "10/18/2021",
    caseName: "Addison, Lavaunda Vs. South Carolina Dept Of Trans",
    division: "South Carolina",
    assignedTo: "",
    comments: [
      {
        id: 1,
        title: "Comment 1",
        description: "First Comment for task Stich MPEG",
        createdBy: "gjames@veritext.com",
      },
      {
        id: 2,
        title: "Comment 2",
        description: "Second Comment for task Stich MPEG",
        createdBy: "gjames@veritext.com",
      },
    ],
    history: [
      {
        id: 1,
        description: "Assigned to gjames",
        date: "11/1/2021",
      },
      {
        id: 2,
        description: "Claimed by cgalinda",
        date: "11/2/2021",
      },
    ],
  },
  {
    id: 4,
    jobNumber: 9847463,
    processName: "Produce MP4",
    name: "QC Files/ Prepare PIP Video/ Review",
    dueDate: "10/21/2021",
    status: "overdue",
    priority: "urgent",
    earliestVideoOrderDays: 5,
    earliestVideoOrderDueDate: "10/18/2021",
    caseName: "In Re Brenn De Bree, Et Al.",
    division: "Dallas",
    assignedTo: "",
    comments: [
      {
        id: 1,
        title: "Comment 1",
        description:
          "First Comment for task QC Files/ Prepare PIP Video/ Review",
        createdBy: "gjames@veritext.com",
      },
      {
        id: 2,
        title: "Comment 2",
        description:
          "Second Comment for task QC Files/ Prepare PIP Video/ Review",
        createdBy: "gjames@veritext.com",
      },
    ],
    history: [
      {
        id: 1,
        description: "Assigned to gjames",
        date: "11/1/2021",
      },
      {
        id: 2,
        description: "Claimed by cgalinda",
        date: "11/2/2021",
      },
    ],
  },
  {
    id: 5,
    jobNumber: 1123434,
    processName: "Produce MP4",
    name: "QC Files/ Prepare PIP Video/ Review",
    dueDate: "10/21/2021",
    status: "complete",
    priority: "urgent",
    earliestVideoOrderDays: 5,
    earliestVideoOrderDueDate: "10/18/2021",
    caseName: "In Re Brenn De Bree, Et Al.",
    division: "Dallas",
    assignedTo: "",
  },
  {
    id: 6,
    jobNumber: 7463846,
    processName: "Produce MP4",
    name: "QC Files/ Prepare PIP Video/ Review",
    dueDate: "10/21/2021",
    status: "assigned",
    priority: "high",
    earliestVideoOrderDays: 5,
    earliestVideoOrderDueDate: "10/18/2021",
    caseName: "In Re Brenn De Bree, Et Al.",
    division: "Dallas",
    assignedTo: "mdrenkalo",
  },
  {
    id: 7,
    jobNumber: 3490954,
    processName: "Produce MP4",
    name: "QC Files/ Prepare PIP Video/ Review",
    dueDate: "10/21/2021",
    status: "assigned",
    priority: "high",
    earliestVideoOrderDays: 5,
    earliestVideoOrderDueDate: "10/18/2021",
    caseName: "In Re Brenn De Bree, Et Al.",
    division: "Dallas",
    assignedTo: "guy",
  }
]
